name: tests

on: [pull_request, push]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        database_url:
          - postgres://postgres:postgres@/django_relativity
          - sqlite://
        django_version: ["3.2", "4.0", "4.1", "4.2"]
        python_version: ["3.8", "3.9", "3.10", "3.11"]
        include:
          - {django_version: "3.2", python_version: "3.6", database_url: "postgres://postgres:postgres@/django_relativity"}
          - {django_version: "3.2", python_version: "3.6", database_url: "sqlite://"}
          - {django_version: "3.2", python_version: "3.7", database_url: "postgres://postgres:postgres@/django_relativity"}
          - {django_version: "3.2", python_version: "3.7", database_url: "sqlite://"}
        exclude:
          - {django_version: "3.2", python_version: "3.11"}
          - {django_version: "4.0", python_version: "3.11"}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - run: make test
        env:
          DJANGO_VERSION: ${{ matrix.django_version }}
          DATABASE_URL: ${{ matrix.database_url }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
