name: tests

on: [pull_request, push]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        database_url:
          - postgres://postgres:postgres@postgres/django_relativity
          - sqlite://
          - mysql://root:mysql@mysql/django_relativity
        django_version: ["3.2", "4.0", "4.1", "4.2"]
        python_version: ["3.8", "3.9", "3.10", "3.11"]
        include:
          - {django_version: "3.2", python_version: "3.6", database_url: "postgres://postgres:postgres@postgres/django_relativity"}
          - {django_version: "3.2", python_version: "3.6", database_url: "sqlite://"}
          - {django_version: "3.2", python_version: "3.6", database_url: "mysql://root:mysql@mysql/django_relativity"}
          - {django_version: "3.2", python_version: "3.7", database_url: "postgres://postgres:postgres@postgres/django_relativity"}
          - {django_version: "3.2", python_version: "3.7", database_url: "sqlite://"}
          - {django_version: "3.2", python_version: "3.7", database_url: "mysql://root:mysql@mysql/django_relativity"}
        exclude:
          - {django_version: "3.2", python_version: "3.11"}
          - {django_version: "4.0", python_version: "3.11"}
    runs-on: ubuntu-latest
    container: python:${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v3
      - run: make test
        env:
          DJANGO_VERSION: ${{ matrix.django_version }}
          DATABASE_URL: ${{ matrix.database_url }}
    services:
      mysql:
        image: ${{ startsWith(matrix.database_url, 'mysql') && 'mysql' || '' }}
        env:
          MYSQL_ROOT_PASSWORD: mysql
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
      postgres:
        image: ${{ startsWith(matrix.database_url, 'postgres') && 'postgres' || '' }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
